services:
  valkey:
    image: valkey/valkey:latest
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./Database/init:/docker-entrypoint-initdb.d

  otel:
    otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
    environment:
      - OTEL_LOG_LEVEL=debug

  swift:
    image: swift:latest
    restart: always
    depends_on:
      - postgres
      - valkey
      - otel
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      APPLE_APP_ID: ${APPLE_APP_ID}
      VALKEY_HOSTNAME: ${VALKEY_HOSTNAME}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_USER: ${POSTGRES_USER:-test_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      EDDSA_PRIVATE_KEY: ${EDDSA_PRIVATE_KEY}
      RELYING_PARTY_ORIGIN: ${RELYING_PARTY_ORIGIN}
      RELYING_PARTY_ID: ${RELYING_PARTY_ID}
      RELYING_PARTY_NAME: ${RELYING_PARTY_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      OTP_SECRET_KEY: ${OTP_SECRET_KEY}
